//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoooooJu.Web.Core.SetUserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/BoooooJu.Service.Core.Dal")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CellPhoneValidateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmailValidateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordSaltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PasswordSaltTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellPhone {
            get {
                return this.CellPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CellPhoneField, value) != true)) {
                    this.CellPhoneField = value;
                    this.RaisePropertyChanged("CellPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CellPhoneValidate {
            get {
                return this.CellPhoneValidateField;
            }
            set {
                if ((this.CellPhoneValidateField.Equals(value) != true)) {
                    this.CellPhoneValidateField = value;
                    this.RaisePropertyChanged("CellPhoneValidate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAdress {
            get {
                return this.EmailAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAdressField, value) != true)) {
                    this.EmailAdressField = value;
                    this.RaisePropertyChanged("EmailAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmailValidate {
            get {
                return this.EmailValidateField;
            }
            set {
                if ((this.EmailValidateField.Equals(value) != true)) {
                    this.EmailValidateField = value;
                    this.RaisePropertyChanged("EmailValidate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordSalt {
            get {
                return this.PasswordSaltField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordSaltField, value) != true)) {
                    this.PasswordSaltField = value;
                    this.RaisePropertyChanged("PasswordSalt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PasswordSaltType {
            get {
                return this.PasswordSaltTypeField;
            }
            set {
                if ((this.PasswordSaltTypeField.Equals(value) != true)) {
                    this.PasswordSaltTypeField = value;
                    this.RaisePropertyChanged("PasswordSaltType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SetUserService.ISetUser")]
    public interface ISetUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseSetDataOf_User/Insert", ReplyAction="http://tempuri.org/IBaseSetDataOf_User/InsertResponse")]
        BoooooJu.Web.Core.SetUserService.User Insert(BoooooJu.Web.Core.SetUserService.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseSetDataOf_User/Insert", ReplyAction="http://tempuri.org/IBaseSetDataOf_User/InsertResponse")]
        System.Threading.Tasks.Task<BoooooJu.Web.Core.SetUserService.User> InsertAsync(BoooooJu.Web.Core.SetUserService.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseSetDataOf_User/DeleteByPrimaryKey", ReplyAction="http://tempuri.org/IBaseSetDataOf_User/DeleteByPrimaryKeyResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BoooooJu.Web.Core.SetUserService.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        bool DeleteByPrimaryKey(object[] keyValues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseSetDataOf_User/DeleteByPrimaryKey", ReplyAction="http://tempuri.org/IBaseSetDataOf_User/DeleteByPrimaryKeyResponse")]
        System.Threading.Tasks.Task<bool> DeleteByPrimaryKeyAsync(object[] keyValues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseSetDataOf_User/UpdateByPrimaryKey", ReplyAction="http://tempuri.org/IBaseSetDataOf_User/UpdateByPrimaryKeyResponse")]
        BoooooJu.Web.Core.SetUserService.User UpdateByPrimaryKey(BoooooJu.Web.Core.SetUserService.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseSetDataOf_User/UpdateByPrimaryKey", ReplyAction="http://tempuri.org/IBaseSetDataOf_User/UpdateByPrimaryKeyResponse")]
        System.Threading.Tasks.Task<BoooooJu.Web.Core.SetUserService.User> UpdateByPrimaryKeyAsync(BoooooJu.Web.Core.SetUserService.User t);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISetUserChannel : BoooooJu.Web.Core.SetUserService.ISetUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SetUserClient : System.ServiceModel.ClientBase<BoooooJu.Web.Core.SetUserService.ISetUser>, BoooooJu.Web.Core.SetUserService.ISetUser {
        
        public SetUserClient() {
        }
        
        public SetUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SetUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SetUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SetUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BoooooJu.Web.Core.SetUserService.User Insert(BoooooJu.Web.Core.SetUserService.User t) {
            return base.Channel.Insert(t);
        }
        
        public System.Threading.Tasks.Task<BoooooJu.Web.Core.SetUserService.User> InsertAsync(BoooooJu.Web.Core.SetUserService.User t) {
            return base.Channel.InsertAsync(t);
        }
        
        public bool DeleteByPrimaryKey(object[] keyValues) {
            return base.Channel.DeleteByPrimaryKey(keyValues);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteByPrimaryKeyAsync(object[] keyValues) {
            return base.Channel.DeleteByPrimaryKeyAsync(keyValues);
        }
        
        public BoooooJu.Web.Core.SetUserService.User UpdateByPrimaryKey(BoooooJu.Web.Core.SetUserService.User t) {
            return base.Channel.UpdateByPrimaryKey(t);
        }
        
        public System.Threading.Tasks.Task<BoooooJu.Web.Core.SetUserService.User> UpdateByPrimaryKeyAsync(BoooooJu.Web.Core.SetUserService.User t) {
            return base.Channel.UpdateByPrimaryKeyAsync(t);
        }
    }
}
