// <auto-generated />
namespace BoooooJu.Service.Core.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BooooJuDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BooooJuDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201601211122085_BooooJuDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
