//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoooooJu.Web.Core.TestService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestService.IMySimpleService")]
    public interface IMySimpleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySimpleService/Hello", ReplyAction="http://tempuri.org/IMySimpleService/HelloResponse")]
        string Hello([System.ServiceModel.MessageParameterAttribute(Name="hello")] string hello1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySimpleService/Hello", ReplyAction="http://tempuri.org/IMySimpleService/HelloResponse")]
        System.Threading.Tasks.Task<string> HelloAsync(string hello);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMySimpleServiceChannel : BoooooJu.Web.Core.TestService.IMySimpleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MySimpleServiceClient : System.ServiceModel.ClientBase<BoooooJu.Web.Core.TestService.IMySimpleService>, BoooooJu.Web.Core.TestService.IMySimpleService {
        
        public MySimpleServiceClient() {
        }
        
        public MySimpleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MySimpleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySimpleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySimpleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Hello(string hello1) {
            return base.Channel.Hello(hello1);
        }
        
        public System.Threading.Tasks.Task<string> HelloAsync(string hello) {
            return base.Channel.HelloAsync(hello);
        }
    }
}
