//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoooooJu.Web.Core.DiancanService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DC_User", Namespace="http://schemas.datacontract.org/2004/07/BoooooJu.Service.DPModels")]
    [System.SerializableAttribute()]
    public partial class DC_User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PCAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PCAddress {
            get {
                return this.PCAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PCAddressField, value) != true)) {
                    this.PCAddressField = value;
                    this.RaisePropertyChanged("PCAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DC_Order", Namespace="http://schemas.datacontract.org/2004/07/BoooooJu.Service.DPModels")]
    [System.SerializableAttribute()]
    public partial class DC_Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FoodIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FoodId {
            get {
                return this.FoodIdField;
            }
            set {
                if ((this.FoodIdField.Equals(value) != true)) {
                    this.FoodIdField = value;
                    this.RaisePropertyChanged("FoodId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderTime {
            get {
                return this.OrderTimeField;
            }
            set {
                if ((this.OrderTimeField.Equals(value) != true)) {
                    this.OrderTimeField = value;
                    this.RaisePropertyChanged("OrderTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Page", Namespace="http://schemas.datacontract.org/2004/07/BoooooJu.Service.Core.QueryParameter")]
    [System.SerializableAttribute()]
    public partial class Page : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BoooooJu.Web.Core.DiancanService.Sort SortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BoooooJu.Web.Core.DiancanService.Sort Sort {
            get {
                return this.SortField;
            }
            set {
                if ((this.SortField.Equals(value) != true)) {
                    this.SortField = value;
                    this.RaisePropertyChanged("Sort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCounts {
            get {
                return this.TotalCountsField;
            }
            set {
                if ((this.TotalCountsField.Equals(value) != true)) {
                    this.TotalCountsField = value;
                    this.RaisePropertyChanged("TotalCounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sort", Namespace="http://schemas.datacontract.org/2004/07/BoooooJu.Service.Core.QueryParameter.Base" +
        "")]
    public enum Sort : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Asc = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Desc = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DC_OBOrder_Rank", Namespace="http://schemas.datacontract.org/2004/07/BoooooJu.Service.Core.Dal.Rank")]
    public enum DC_OBOrder_Rank : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrderId = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrderTime = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateTime = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserId = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserName = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FoodId = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FoodName = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OBDC_Order", Namespace="http://schemas.datacontract.org/2004/07/BoooooJu.Service.Core.Dal.OBModels")]
    [System.SerializableAttribute()]
    public partial class OBDC_Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FoodIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FoodId {
            get {
                return this.FoodIdField;
            }
            set {
                if ((this.FoodIdField.Equals(value) != true)) {
                    this.FoodIdField = value;
                    this.RaisePropertyChanged("FoodId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName {
            get {
                return this.FoodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodNameField, value) != true)) {
                    this.FoodNameField = value;
                    this.RaisePropertyChanged("FoodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderTime {
            get {
                return this.OrderTimeField;
            }
            set {
                if ((this.OrderTimeField.Equals(value) != true)) {
                    this.OrderTimeField = value;
                    this.RaisePropertyChanged("OrderTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((this.UpdateTimeField.Equals(value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DC_Food", Namespace="http://schemas.datacontract.org/2004/07/BoooooJu.Service.DPModels")]
    [System.SerializableAttribute()]
    public partial class DC_Food : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enable {
            get {
                return this.EnableField;
            }
            set {
                if ((this.EnableField.Equals(value) != true)) {
                    this.EnableField = value;
                    this.RaisePropertyChanged("Enable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DiancanService.IDiancanService")]
    public interface IDiancanService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/AddUser", ReplyAction="http://tempuri.org/IDiancanService/AddUserResponse")]
        BoooooJu.Web.Core.DiancanService.DC_User AddUser(BoooooJu.Web.Core.DiancanService.DC_User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/AddUser", ReplyAction="http://tempuri.org/IDiancanService/AddUserResponse")]
        System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_User> AddUserAsync(BoooooJu.Web.Core.DiancanService.DC_User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/UpdateUser", ReplyAction="http://tempuri.org/IDiancanService/UpdateUserResponse")]
        BoooooJu.Web.Core.DiancanService.DC_User UpdateUser(BoooooJu.Web.Core.DiancanService.DC_User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/UpdateUser", ReplyAction="http://tempuri.org/IDiancanService/UpdateUserResponse")]
        System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_User> UpdateUserAsync(BoooooJu.Web.Core.DiancanService.DC_User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/FindUserByName", ReplyAction="http://tempuri.org/IDiancanService/FindUserByNameResponse")]
        BoooooJu.Web.Core.DiancanService.DC_User FindUserByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/FindUserByName", ReplyAction="http://tempuri.org/IDiancanService/FindUserByNameResponse")]
        System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_User> FindUserByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/FindUsersByIp", ReplyAction="http://tempuri.org/IDiancanService/FindUsersByIpResponse")]
        BoooooJu.Web.Core.DiancanService.DC_User[] FindUsersByIp(string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/FindUsersByIp", ReplyAction="http://tempuri.org/IDiancanService/FindUsersByIpResponse")]
        System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_User[]> FindUsersByIpAsync(string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/PlaceOrder", ReplyAction="http://tempuri.org/IDiancanService/PlaceOrderResponse")]
        BoooooJu.Web.Core.DiancanService.DC_Order PlaceOrder(BoooooJu.Web.Core.DiancanService.DC_Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/PlaceOrder", ReplyAction="http://tempuri.org/IDiancanService/PlaceOrderResponse")]
        System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_Order> PlaceOrderAsync(BoooooJu.Web.Core.DiancanService.DC_Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/DeleteOrderById", ReplyAction="http://tempuri.org/IDiancanService/DeleteOrderByIdResponse")]
        bool DeleteOrderById(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/DeleteOrderById", ReplyAction="http://tempuri.org/IDiancanService/DeleteOrderByIdResponse")]
        System.Threading.Tasks.Task<bool> DeleteOrderByIdAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/UpdateOrder", ReplyAction="http://tempuri.org/IDiancanService/UpdateOrderResponse")]
        BoooooJu.Web.Core.DiancanService.DC_Order UpdateOrder(BoooooJu.Web.Core.DiancanService.DC_Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/UpdateOrder", ReplyAction="http://tempuri.org/IDiancanService/UpdateOrderResponse")]
        System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_Order> UpdateOrderAsync(BoooooJu.Web.Core.DiancanService.DC_Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/GetTodayOrder", ReplyAction="http://tempuri.org/IDiancanService/GetTodayOrderResponse")]
        BoooooJu.Web.Core.DiancanService.DC_Order GetTodayOrder(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/GetTodayOrder", ReplyAction="http://tempuri.org/IDiancanService/GetTodayOrderResponse")]
        System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_Order> GetTodayOrderAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/GetOrders", ReplyAction="http://tempuri.org/IDiancanService/GetOrdersResponse")]
        System.Collections.Generic.KeyValuePair<BoooooJu.Web.Core.DiancanService.Page, BoooooJu.Web.Core.DiancanService.OBDC_Order[]> GetOrders(BoooooJu.Web.Core.DiancanService.Page page, BoooooJu.Web.Core.DiancanService.DC_OBOrder_Rank rank);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/GetOrders", ReplyAction="http://tempuri.org/IDiancanService/GetOrdersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<BoooooJu.Web.Core.DiancanService.Page, BoooooJu.Web.Core.DiancanService.OBDC_Order[]>> GetOrdersAsync(BoooooJu.Web.Core.DiancanService.Page page, BoooooJu.Web.Core.DiancanService.DC_OBOrder_Rank rank);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/FindEnableFoods", ReplyAction="http://tempuri.org/IDiancanService/FindEnableFoodsResponse")]
        BoooooJu.Web.Core.DiancanService.DC_Food[] FindEnableFoods();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiancanService/FindEnableFoods", ReplyAction="http://tempuri.org/IDiancanService/FindEnableFoodsResponse")]
        System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_Food[]> FindEnableFoodsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiancanServiceChannel : BoooooJu.Web.Core.DiancanService.IDiancanService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiancanServiceClient : System.ServiceModel.ClientBase<BoooooJu.Web.Core.DiancanService.IDiancanService>, BoooooJu.Web.Core.DiancanService.IDiancanService {
        
        public DiancanServiceClient() {
        }
        
        public DiancanServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiancanServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiancanServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiancanServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BoooooJu.Web.Core.DiancanService.DC_User AddUser(BoooooJu.Web.Core.DiancanService.DC_User user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_User> AddUserAsync(BoooooJu.Web.Core.DiancanService.DC_User user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public BoooooJu.Web.Core.DiancanService.DC_User UpdateUser(BoooooJu.Web.Core.DiancanService.DC_User user) {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_User> UpdateUserAsync(BoooooJu.Web.Core.DiancanService.DC_User user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public BoooooJu.Web.Core.DiancanService.DC_User FindUserByName(string name) {
            return base.Channel.FindUserByName(name);
        }
        
        public System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_User> FindUserByNameAsync(string name) {
            return base.Channel.FindUserByNameAsync(name);
        }
        
        public BoooooJu.Web.Core.DiancanService.DC_User[] FindUsersByIp(string ip) {
            return base.Channel.FindUsersByIp(ip);
        }
        
        public System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_User[]> FindUsersByIpAsync(string ip) {
            return base.Channel.FindUsersByIpAsync(ip);
        }
        
        public BoooooJu.Web.Core.DiancanService.DC_Order PlaceOrder(BoooooJu.Web.Core.DiancanService.DC_Order order) {
            return base.Channel.PlaceOrder(order);
        }
        
        public System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_Order> PlaceOrderAsync(BoooooJu.Web.Core.DiancanService.DC_Order order) {
            return base.Channel.PlaceOrderAsync(order);
        }
        
        public bool DeleteOrderById(int orderId) {
            return base.Channel.DeleteOrderById(orderId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteOrderByIdAsync(int orderId) {
            return base.Channel.DeleteOrderByIdAsync(orderId);
        }
        
        public BoooooJu.Web.Core.DiancanService.DC_Order UpdateOrder(BoooooJu.Web.Core.DiancanService.DC_Order order) {
            return base.Channel.UpdateOrder(order);
        }
        
        public System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_Order> UpdateOrderAsync(BoooooJu.Web.Core.DiancanService.DC_Order order) {
            return base.Channel.UpdateOrderAsync(order);
        }
        
        public BoooooJu.Web.Core.DiancanService.DC_Order GetTodayOrder(int userId) {
            return base.Channel.GetTodayOrder(userId);
        }
        
        public System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_Order> GetTodayOrderAsync(int userId) {
            return base.Channel.GetTodayOrderAsync(userId);
        }
        
        public System.Collections.Generic.KeyValuePair<BoooooJu.Web.Core.DiancanService.Page, BoooooJu.Web.Core.DiancanService.OBDC_Order[]> GetOrders(BoooooJu.Web.Core.DiancanService.Page page, BoooooJu.Web.Core.DiancanService.DC_OBOrder_Rank rank) {
            return base.Channel.GetOrders(page, rank);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<BoooooJu.Web.Core.DiancanService.Page, BoooooJu.Web.Core.DiancanService.OBDC_Order[]>> GetOrdersAsync(BoooooJu.Web.Core.DiancanService.Page page, BoooooJu.Web.Core.DiancanService.DC_OBOrder_Rank rank) {
            return base.Channel.GetOrdersAsync(page, rank);
        }
        
        public BoooooJu.Web.Core.DiancanService.DC_Food[] FindEnableFoods() {
            return base.Channel.FindEnableFoods();
        }
        
        public System.Threading.Tasks.Task<BoooooJu.Web.Core.DiancanService.DC_Food[]> FindEnableFoodsAsync() {
            return base.Channel.FindEnableFoodsAsync();
        }
    }
}
